import os

SAVE_PATH = os.path.join(".", "saves")
SAVE_FILE_TITLE = "save.txt"
TABLE_COLS = 5
ENTITIES_PER_PAGE = 5
GAME_NEW_PARSE_TIME = 60
STOP_WORD = "Завер"
TABLE_UPDATE_TIME = GAME_NEW_PARSE_TIME / 2